import type {
  UserDto,
  UserResponse,
  RoleDto,
  VersionResponse,
  ClientResponse,
  ClientVersionHistory,
  CRFResponse,
  CRFClientResponse,
  CRFApprovalResponse,
  DeploymentLogResponse,
  WorkflowStepResponse,
  APIConfigurationResponse,
  APIExecutionLogResponse,
  ErrorNotificationResponse,
  DeploymentQueueResponse,
  NotificationResponse,
  AuditLogResponse,
  BulkOperationResponse,
  DashboardStatisticsResponse,
  DeploymentReportResponse,
  CRFReportResponse,
  ClientReportResponse,
  SystemPerformanceReportResponse,
  CRFTemplateResponse,
  SystemMetrics,
  SystemHealthResponse,
} from '../services/api';

// Helper to generate dates
const getDateString = (daysOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

const getDateTimeString = (daysOffset: number = 0, hoursOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(date.getHours() + hoursOffset);
  return date.toISOString();
};

// Mock Users
export const mockUsers: UserResponse[] = [
  {
    userId: 1,
    username: 'devops_admin',
    email: 'admin@devops.com',
    firstName: 'John',
    lastName: 'Smith',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-365),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 2,
    username: 'delivery_lead',
    email: 'lead@delivery.com',
    firstName: 'Sarah',
    lastName: 'Johnson',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-300),
    lastLoginDate: getDateTimeString(-2),
  },
  {
    userId: 3,
    username: 'client_acme',
    email: 'it@acmecorp.com',
    firstName: 'Mike',
    lastName: 'Chen',
    company: 'Acme Corporation',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-200),
    lastLoginDate: getDateTimeString(-5),
  },
  {
    userId: 4,
    username: 'devops_engineer',
    email: 'engineer@devops.com',
    firstName: 'Emily',
    lastName: 'Davis',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-180),
    lastLoginDate: getDateTimeString(0),
  },
  {
    userId: 5,
    username: 'delivery_tech',
    email: 'tech@delivery.com',
    firstName: 'Robert',
    lastName: 'Wilson',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-150),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 6,
    username: 'client_global',
    email: 'it@globaltech.com',
    firstName: 'Lisa',
    lastName: 'Martinez',
    company: 'Global Tech Industries',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-120),
    lastLoginDate: getDateTimeString(-3),
  },
  {
    userId: 7,
    username: 'client_innovate',
    email: 'admin@innovatesolutions.com',
    firstName: 'David',
    lastName: 'Park',
    company: 'Innovate Solutions',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-90),
    lastLoginDate: getDateTimeString(-7),
  },
  {
    userId: 8,
    username: 'devops_senior',
    email: 'senior@devops.com',
    firstName: 'Marcus',
    lastName: 'Thompson',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-320),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 9,
    username: 'delivery_manager',
    email: 'manager@delivery.com',
    firstName: 'Amanda',
    lastName: 'Rodriguez',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-280),
    lastLoginDate: getDateTimeString(-2),
  },
  {
    userId: 10,
    username: 'client_techstart',
    email: 'ops@techstart.com',
    firstName: 'Kevin',
    lastName: 'Brown',
    company: 'TechStart Inc',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-120),
    lastLoginDate: getDateTimeString(-15),
  },
  {
    userId: 11,
    username: 'client_datacore',
    email: 'admin@datacore.com',
    firstName: 'Sandra',
    lastName: 'Lee',
    company: 'DataCore Systems',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-500),
    lastLoginDate: getDateTimeString(-4),
  },
  {
    userId: 12,
    username: 'devops_junior',
    email: 'junior@devops.com',
    firstName: 'Tyler',
    lastName: 'Anderson',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-90),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 13,
    username: 'delivery_specialist',
    email: 'specialist@delivery.com',
    firstName: 'Nicole',
    lastName: 'White',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-200),
    lastLoginDate: getDateTimeString(-3),
  },
  {
    userId: 14,
    username: 'client_cloudnative',
    email: 'it@cloudnative.com',
    firstName: 'James',
    lastName: 'Miller',
    company: 'CloudNative Corp',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-400),
    lastLoginDate: getDateTimeString(-2),
  },
  {
    userId: 15,
    username: 'client_fintech',
    email: 'ops@fintechsolutions.com',
    firstName: 'Patricia',
    lastName: 'Garcia',
    company: 'FinTech Solutions',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-350),
    lastLoginDate: getDateTimeString(-6),
  },
  {
    userId: 16,
    username: 'client_healthtech',
    email: 'admin@healthtech.com',
    firstName: 'Christopher',
    lastName: 'Martinez',
    company: 'HealthTech Systems',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-280),
    lastLoginDate: getDateTimeString(-8),
  },
  {
    userId: 17,
    username: 'client_ecommerce',
    email: 'it@ecommercepro.com',
    firstName: 'Jessica',
    lastName: 'Taylor',
    company: 'E-Commerce Pro',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-220),
    lastLoginDate: getDateTimeString(-5),
  },
  {
    userId: 18,
    username: 'client_manufacturing',
    email: 'tech@manufact.com',
    firstName: 'Daniel',
    lastName: 'Thomas',
    company: 'Manufacturing Tech Inc',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-310),
    lastLoginDate: getDateTimeString(-10),
  },
  {
    userId: 19,
    username: 'delivery_coordinator',
    email: 'coordinator@delivery.com',
    firstName: 'Michelle',
    lastName: 'Jackson',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-140),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 20,
    username: 'client_logistics',
    email: 'systems@logisticsplus.com',
    firstName: 'Brian',
    lastName: 'Harris',
    company: 'Logistics Plus',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-260),
    lastLoginDate: getDateTimeString(-12),
  },
  {
    userId: 21,
    username: 'client_retail',
    email: 'it@retailchain.com',
    firstName: 'Angela',
    lastName: 'Clark',
    company: 'Retail Chain Solutions',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-190),
    lastLoginDate: getDateTimeString(-7),
  },
  {
    userId: 22,
    username: 'client_education',
    email: 'admin@edutech.com',
    firstName: 'Steven',
    lastName: 'Lewis',
    company: 'EduTech Platform',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-230),
    lastLoginDate: getDateTimeString(-14),
  },
  {
    userId: 23,
    username: 'client_insurance',
    email: 'ops@insurancetech.com',
    firstName: 'Laura',
    lastName: 'Walker',
    company: 'InsuranceTech Group',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-340),
    lastLoginDate: getDateTimeString(-9),
  },
  {
    userId: 24,
    username: 'client_telecom',
    email: 'tech@telecomcorp.com',
    firstName: 'Ryan',
    lastName: 'Hall',
    company: 'Telecom Corporation',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-270),
    lastLoginDate: getDateTimeString(-11),
  },
  {
    userId: 25,
    username: 'devops_architect',
    email: 'architect@devops.com',
    firstName: 'Monica',
    lastName: 'Allen',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-420),
    lastLoginDate: getDateTimeString(0),
  },
];

export const mockUserDtos: UserDto[] = mockUsers.map(u => ({
  userId: u.userId,
  username: u.username,
  email: u.email,
  firstName: u.firstName,
  lastName: u.lastName,
  company: u.company,
  role: u.roles,
  isActive: u.isActive,
  lastLoginDate: u.lastLoginDate,
}));

// Mock Roles
export const mockRoles: RoleDto[] = [
  {
    roleId: 1,
    roleName: 'DevOps',
    description: 'Full system access including API configuration and all management features',
    isActive: true,
  },
  {
    roleId: 2,
    roleName: 'Delivery',
    description: 'Limited access to dashboard, versions, workflow, clients, history, and reporting',
    isActive: true,
  },
  {
    roleId: 3,
    roleName: 'Client',
    description: 'Access only to versions and their own update history',
    isActive: true,
  },
];

// Mock Versions
export const mockVersions: VersionResponse[] = [
  {
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    releaseDate: getDateString(-30),
    description: 'Latest stable release with security enhancements',
    releaseNotes: 'Enhanced security protocols, improved performance, new dashboard widgets',
    isMajorRelease: false,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-35),
    updatedDate: getDateString(-30),
    clientCount: 8,
  },
  {
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    releaseDate: getDateString(-90),
    description: 'Major feature update with new reporting module',
    releaseNotes: 'New reporting module, multi-language support, CRM integrations',
    isMajorRelease: true,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-100),
    updatedDate: getDateString(-90),
    clientCount: 15,
  },
  {
    versionId: 3,
    versionNumber: '3.1.5',
    versionName: 'Summer 2024 Patch',
    releaseDate: getDateString(-150),
    description: 'Bug fixes and UI improvements',
    releaseNotes: 'UI/UX improvements, email notification templates, advanced search filters',
    isMajorRelease: false,
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-160),
    updatedDate: getDateString(-150),
    clientCount: 22,
  },
  {
    versionId: 4,
    versionNumber: '3.1.0',
    versionName: 'Spring 2024 Release',
    releaseDate: getDateString(-210),
    description: 'Initial 3.1 series release',
    releaseNotes: 'Redesigned admin panel, new user role management system',
    isMajorRelease: true,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-220),
    clientCount: 10,
  },
  {
    versionId: 5,
    versionNumber: '3.0.8',
    versionName: 'Legacy Stable',
    releaseDate: getDateString(-300),
    description: 'Legacy version - End of life',
    releaseNotes: 'Final security patches for 3.0 series',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-310),
    clientCount: 3,
  },
  {
    versionId: 6,
    versionNumber: '3.0.7',
    versionName: 'Legacy Patch 7',
    releaseDate: getDateString(-330),
    description: 'Security patches for legacy version',
    releaseNotes: 'Critical security fixes, performance improvements',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-340),
    updatedDate: getDateString(-330),
    clientCount: 1,
  },
  {
    versionId: 7,
    versionNumber: '3.0.5',
    versionName: 'Legacy Patch 5',
    releaseDate: getDateString(-360),
    description: 'Bug fixes for legacy version',
    releaseNotes: 'Various bug fixes and stability improvements',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-370),
    updatedDate: getDateString(-360),
    clientCount: 0,
  },
  {
    versionId: 8,
    versionNumber: '2.9.0',
    versionName: 'End of Life Release',
    releaseDate: getDateString(-400),
    description: 'Final 2.x series release',
    releaseNotes: 'End of life announcement, upgrade path to 3.x',
    isMajorRelease: true,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-410),
    clientCount: 0,
  },
  {
    versionId: 9,
    versionNumber: '3.1.8',
    versionName: 'Summer 2024 Hotfix',
    releaseDate: getDateString(-120),
    description: 'Critical hotfix for 3.1.5',
    releaseNotes: 'Fixed critical authentication bug, improved session management',
    isMajorRelease: false,
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-125),
    updatedDate: getDateString(-120),
    clientCount: 12,
  },
  {
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    releaseDate: getDateString(-10),
    description: 'Latest hotfix with performance improvements',
    releaseNotes: 'Performance optimization, memory leak fixes, UI improvements',
    isMajorRelease: false,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-15),
    updatedDate: getDateString(-10),
    clientCount: 3,
  },
  {
    versionId: 11,
    versionNumber: '3.0.3',
    versionName: 'Legacy Patch 3',
    releaseDate: getDateString(-420),
    description: 'Early legacy patch',
    releaseNotes: 'UI fixes, minor security updates',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-430),
    clientCount: 0,
  },
  {
    versionId: 12,
    versionNumber: '3.1.3',
    versionName: 'Spring 2024 Patch',
    releaseDate: getDateString(-180),
    description: 'Bug fixes for Spring release',
    releaseNotes: 'Fixed login issues, improved data export functionality',
    isMajorRelease: false,
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-190),
    updatedDate: getDateString(-180),
    clientCount: 8,
  },
  {
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    releaseDate: getDateString(30),
    description: 'Upcoming release with AI features',
    releaseNotes: 'AI-powered analytics, enhanced reporting, new integrations',
    isMajorRelease: false,
    isActive: true,
    createdBy: 25,
    createdByName: 'Monica Allen',
    createdDate: getDateString(10),
    updatedDate: getDateString(15),
    clientCount: 0,
  },
  {
    versionId: 14,
    versionNumber: '3.1.2',
    versionName: 'Spring 2024 Hotfix 2',
    releaseDate: getDateString(-195),
    description: 'Emergency hotfix',
    releaseNotes: 'Critical security vulnerability patch',
    isMajorRelease: false,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-196),
    updatedDate: getDateString(-195),
    clientCount: 5,
  },
  {
    versionId: 15,
    versionNumber: '3.0.0',
    versionName: 'Major Release 3.0',
    releaseDate: getDateString(-450),
    description: 'Major version 3.0 initial release',
    releaseNotes: 'Complete platform redesign, new architecture, enhanced security',
    isMajorRelease: true,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-460),
    clientCount: 0,
  },
];

// Mock Clients
export const mockClients: ClientResponse[] = [
  {
    clientId: 1,
    clientName: 'Acme Corporation',
    contactEmail: 'it@acmecorp.com',
    contactPerson: 'Mike Chen',
    phone: '+1-555-0101',
    address: '123 Business St, New York, NY 10001',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-150),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-365),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 2,
    clientName: 'Global Tech Industries',
    contactEmail: 'it@globaltech.com',
    contactPerson: 'Lisa Martinez',
    phone: '+1-555-0102',
    address: '456 Tech Ave, San Francisco, CA 94102',
    currentVersionId: 1,
    currentVersion: '3.2.1',
    currentVersionName: 'Winter 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-25),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-300),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 3,
    clientName: 'Innovate Solutions',
    contactEmail: 'admin@innovatesolutions.com',
    contactPerson: 'David Park',
    phone: '+1-555-0103',
    address: '789 Innovation Dr, Austin, TX 78701',
    currentVersionId: 2,
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-85),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-250),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    contactEmail: 'support@enterprisesys.com',
    contactPerson: 'Jennifer Adams',
    phone: '+1-555-0104',
    address: '321 Enterprise Blvd, Chicago, IL 60601',
    currentVersionId: 4,
    currentVersion: '3.1.0',
    currentVersionName: 'Spring 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-205),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-400),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 5,
    clientName: 'Digital Dynamics',
    contactEmail: 'ops@digitaldynamics.com',
    contactPerson: 'Alex Martinez',
    phone: '+1-555-0105',
    address: '555 Digital Way, Seattle, WA 98101',
    currentVersionId: 1,
    currentVersion: '3.2.1',
    currentVersionName: 'Winter 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-28),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-180),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 6,
    clientName: 'TechStart Inc',
    contactEmail: 'tech@techstart.com',
    contactPerson: 'Rachel Green',
    phone: '+1-555-0106',
    address: '888 Startup Lane, Boston, MA 02101',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Inactive',
    lastUpdateDate: getDateString(-145),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-120),
    isActive: false,
    hasCustomizations: false,
  },
  {
    clientId: 7,
    clientName: 'CloudFirst Solutions',
    contactEmail: 'admin@cloudfirst.com',
    contactPerson: 'Tom Anderson',
    phone: '+1-555-0107',
    address: '999 Cloud St, Denver, CO 80201',
    currentVersionId: 2,
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-88),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-200),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 8,
    clientName: 'DataCore Systems',
    contactEmail: 'it@datacore.com',
    contactPerson: 'Sandra Lee',
    phone: '+1-555-0108',
    address: '777 Data Pkwy, Miami, FL 33101',
    currentVersionId: 5,
    currentVersion: '3.0.8',
    currentVersionName: 'Legacy Stable',
    status: 'Active',
    lastUpdateDate: getDateString(-295),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-500),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
];

// Mock Client Version History
export const mockClientVersionHistory: ClientVersionHistory[] = [
  {
    clientVersionId: 1,
    clientId: 1,
    versionId: 3,
    versionNumber: '3.1.5',
    versionName: 'Summer 2024 Patch',
    assignedDate: getDateString(-150),
    updatedBy: 1,
    updatedByName: 'John Smith',
    notes: 'Routine update with UI improvements',
    isCurrentVersion: true,
  },
  {
    clientVersionId: 2,
    clientId: 1,
    versionId: 4,
    versionNumber: '3.1.0',
    versionName: 'Spring 2024 Release',
    assignedDate: getDateString(-210),
    updatedBy: 1,
    updatedByName: 'John Smith',
    notes: 'Major version upgrade',
    isCurrentVersion: false,
  },
  {
    clientVersionId: 3,
    clientId: 2,
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    assignedDate: getDateString(-25),
    updatedBy: 4,
    updatedByName: 'Emily Davis',
    notes: 'Security patches applied successfully',
    isCurrentVersion: true,
  },
  {
    clientVersionId: 4,
    clientId: 2,
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    assignedDate: getDateString(-90),
    updatedBy: 1,
    updatedByName: 'John Smith',
    notes: 'New reporting features enabled',
    isCurrentVersion: false,
  },
  {
    clientVersionId: 5,
    clientId: 3,
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    assignedDate: getDateString(-85),
    updatedBy: 2,
    updatedByName: 'Sarah Johnson',
    notes: 'Standard deployment',
    isCurrentVersion: true,
  },
  {
    clientVersionId: 6,
    clientId: 5,
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    assignedDate: getDateString(-28),
    updatedBy: 2,
    updatedByName: 'Sarah Johnson',
    notes: 'Updated after rollback from failed 3.2.0 deployment',
    isCurrentVersion: true,
  },
  {
    clientVersionId: 7,
    clientId: 5,
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    assignedDate: getDateString(-30),
    updatedBy: 2,
    updatedByName: 'Sarah Johnson',
    notes: 'Deployment failed - rolled back',
    isCurrentVersion: false,
  },
];

// Mock Workflow Steps
export const mockWorkflowSteps: WorkflowStepResponse[] = [
  {
    workflowStepId: 1,
    stepName: 'Request Submission',
    stepOrder: 1,
    isRequired: true,
    isActive: true,
    createdDate: getDateString(-400),
  },
  {
    workflowStepId: 2,
    stepName: 'Application Owner Review',
    stepOrder: 2,
    isRequired: true,
    isActive: true,
    createdDate: getDateString(-400),
  },
  {
    workflowStepId: 3,
    stepName: 'Security Review',
    stepOrder: 3,
    isRequired: false,
    isActive: true,
    createdDate: getDateString(-350),
  },
  {
    workflowStepId: 4,
    stepName: 'IT Department Sign-off',
    stepOrder: 4,
    isRequired: true,
    isActive: true,
    createdDate: getDateString(-400),
  },
  {
    workflowStepId: 5,
    stepName: 'Change Advisory Board',
    stepOrder: 5,
    isRequired: false,
    isActive: false,
    createdDate: getDateString(-300),
  },
];

// Mock CRFs
export const mockCRFs: CRFResponse[] = [
  {
    crfId: 1,
    crfNumber: 'CRF-2024-001',
    title: 'Security Update for Acme Corporation',
    description: 'Deploy security patches and dashboard improvements',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'Pending',
    priority: 'High',
    scheduledDeploymentDate: getDateString(5),
    createdDate: getDateString(-3),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 2,
    crfNumber: 'CRF-2024-002',
    title: 'Minor Version Upgrade - Innovate Solutions',
    description: 'Upgrade from 3.2.0 to 3.2.1',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 5,
    requestedByName: 'Robert Wilson',
    status: 'Approved',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(3),
    createdDate: getDateString(-5),
    updatedDate: getDateString(-1),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 3,
    crfNumber: 'CRF-2024-003',
    title: 'Major Upgrade - Enterprise Systems',
    description: 'Upgrade from 3.1.0 to 3.2.1 with extended maintenance window',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-7),
    actualDeploymentDate: getDateString(-7),
    createdDate: getDateString(-14),
    updatedDate: getDateString(-7),
    completedDate: getDateString(-7),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 4,
    crfNumber: 'CRF-2024-004',
    title: 'Bulk Update - Multiple Clients',
    description: 'Deploy 3.2.1 to multiple clients',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-1),
    actualDeploymentDate: getDateString(-1),
    createdDate: getDateString(-10),
    updatedDate: getDateString(-1),
    clientCount: 3,
    successfulDeployments: 2,
  },
  {
    crfId: 5,
    crfNumber: 'CRF-2023-099',
    title: 'Failed Deployment - Digital Dynamics',
    description: 'Attempted 3.2.0 deployment - rolled back due to database migration timeout',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'Failed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-30),
    actualDeploymentDate: getDateString(-30),
    createdDate: getDateString(-35),
    updatedDate: getDateString(-30),
    completedDate: getDateString(-30),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 6,
    crfNumber: 'CRF-2024-005',
    title: 'Scheduled Maintenance - CloudFirst',
    description: 'Routine patch deployment',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(10),
    createdDate: getDateString(-2),
    clientCount: 1,
    successfulDeployments: 0,
  },
];

// Mock CRF Clients (linking CRFs to Clients)
export const mockCRFClients: CRFClientResponse[] = [
  {
    crfClientId: 1,
    crfId: 1,
    clientId: 1,
    clientName: 'Acme Corporation',
    contactEmail: 'it@acmecorp.com',
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    deploymentStatus: 'Pending',
    deploymentNotes: 'Waiting for CRF approval',
  },
  {
    crfClientId: 2,
    crfId: 2,
    clientId: 3,
    clientName: 'Innovate Solutions',
    contactEmail: 'admin@innovatesolutions.com',
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    deploymentStatus: 'Scheduled',
    deploymentNotes: 'Approved for deployment',
  },
  {
    crfClientId: 3,
    crfId: 3,
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    contactEmail: 'support@enterprisesys.com',
    currentVersion: '3.1.0',
    currentVersionName: 'Spring 2024 Release',
    deploymentStatus: 'Completed',
    deploymentDate: getDateString(-7),
    deploymentNotes: 'Deployment successful',
  },
  {
    crfClientId: 4,
    crfId: 4,
    clientId: 2,
    clientName: 'Global Tech Industries',
    contactEmail: 'it@globaltech.com',
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    deploymentStatus: 'Completed',
    deploymentDate: getDateString(-1),
    deploymentNotes: 'Deployed successfully',
  },
  {
    crfClientId: 5,
    crfId: 4,
    clientId: 5,
    clientName: 'Digital Dynamics',
    contactEmail: 'ops@digitaldynamics.com',
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    deploymentStatus: 'Completed',
    deploymentDate: getDateString(-1),
    deploymentNotes: 'Deployed successfully',
  },
  {
    crfClientId: 6,
    crfId: 4,
    clientId: 7,
    clientName: 'CloudFirst Solutions',
    contactEmail: 'admin@cloudfirst.com',
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    deploymentStatus: 'In Progress',
    deploymentNotes: 'Deployment in progress',
  },
  {
    crfClientId: 7,
    crfId: 5,
    clientId: 5,
    clientName: 'Digital Dynamics',
    contactEmail: 'ops@digitaldynamics.com',
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    deploymentStatus: 'Failed',
    deploymentDate: getDateString(-30),
    deploymentNotes: 'Database migration timeout - rolled back',
  },
  {
    crfClientId: 8,
    crfId: 6,
    clientId: 7,
    clientName: 'CloudFirst Solutions',
    contactEmail: 'admin@cloudfirst.com',
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    deploymentStatus: 'Scheduled',
    deploymentNotes: 'Scheduled for future deployment',
  },
];

// Mock CRF Approvals
export const mockCRFApprovals: CRFApprovalResponse[] = [
  {
    crfApprovalId: 1,
    crfId: 1,
    workflowStepId: 1,
    stepName: 'Request Submission',
    stepOrder: 1,
    approverUserId: 2,
    approverName: 'Sarah Johnson',
    status: 'Approved',
    approvalDate: getDateString(-3),
    comments: 'Urgent security update needed',
    createdDate: getDateString(-3),
  },
  {
    crfApprovalId: 2,
    crfId: 1,
    workflowStepId: 2,
    stepName: 'Application Owner Review',
    stepOrder: 2,
    approverName: 'Pending',
    status: 'Pending',
    comments: '',
    createdDate: getDateString(-3),
  },
  {
    crfApprovalId: 3,
    crfId: 2,
    workflowStepId: 1,
    stepName: 'Request Submission',
    stepOrder: 1,
    approverUserId: 5,
    approverName: 'Robert Wilson',
    status: 'Approved',
    approvalDate: getDateString(-5),
    comments: 'Client requested minor version update',
    createdDate: getDateString(-5),
  },
  {
    crfApprovalId: 4,
    crfId: 2,
    workflowStepId: 2,
    stepName: 'Application Owner Review',
    stepOrder: 2,
    approverUserId: 2,
    approverName: 'Sarah Johnson',
    status: 'Approved',
    approvalDate: getDateString(-2),
    comments: 'Approved - standard update',
    createdDate: getDateString(-5),
  },
  {
    crfApprovalId: 5,
    crfId: 2,
    workflowStepId: 4,
    stepName: 'IT Department Sign-off',
    stepOrder: 4,
    approverUserId: 1,
    approverName: 'John Smith',
    status: 'Approved',
    approvalDate: getDateString(-1),
    comments: 'Final approval granted',
    createdDate: getDateString(-5),
  },
  {
    crfApprovalId: 6,
    crfId: 3,
    workflowStepId: 1,
    stepName: 'Request Submission',
    stepOrder: 1,
    approverUserId: 1,
    approverName: 'John Smith',
    status: 'Approved',
    approvalDate: getDateString(-14),
    comments: 'Major upgrade planned with client coordination',
    createdDate: getDateString(-14),
  },
  {
    crfApprovalId: 7,
    crfId: 3,
    workflowStepId: 2,
    stepName: 'Application Owner Review',
    stepOrder: 2,
    approverUserId: 2,
    approverName: 'Sarah Johnson',
    status: 'Approved',
    approvalDate: getDateString(-12),
    comments: 'Reviewed and approved',
    createdDate: getDateString(-14),
  },
  {
    crfApprovalId: 8,
    crfId: 3,
    workflowStepId: 4,
    stepName: 'IT Department Sign-off',
    stepOrder: 4,
    approverUserId: 1,
    approverName: 'John Smith',
    status: 'Approved',
    approvalDate: getDateString(-10),
    comments: 'All systems ready for deployment',
    createdDate: getDateString(-14),
  },
];

// Mock API Configurations
export const mockAPIConfigurations: APIConfigurationResponse[] = [
  {
    apiConfigurationId: 1,
    apiName: 'Pre-deployment Health Check',
    apiType: 'Deployment',
    httpMethod: 'GET',
    endpointURL: 'https://api.example.com/v1/health/check',
    executionOrder: 1,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: '',
    timeoutSeconds: 30,
    retryCount: 3,
    isEnabled: true,
    description: 'Verify system health before deployment',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 2,
    apiName: 'Create Database Backup',
    apiType: 'Deployment',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/database/backup',
    executionOrder: 2,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', backupType: 'full' }),
    timeoutSeconds: 300,
    retryCount: 2,
    isEnabled: true,
    description: 'Create full database backup before deployment',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 3,
    apiName: 'Deploy New Version',
    apiType: 'Deployment',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/deploy',
    executionOrder: 3,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', version: '{{VERSION}}', environment: '{{ENVIRONMENT}}' }),
    timeoutSeconds: 600,
    retryCount: 1,
    isEnabled: true,
    description: 'Execute deployment of new version',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 4,
    apiName: 'Post-deployment Verification',
    apiType: 'Deployment',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/verify/deployment',
    executionOrder: 4,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', version: '{{VERSION}}', runTests: true }),
    timeoutSeconds: 180,
    retryCount: 2,
    isEnabled: true,
    description: 'Verify deployment success and run tests',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 5,
    apiName: 'Stop Application Services',
    apiType: 'Rollback',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/services/stop',
    executionOrder: 1,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', gracefulShutdown: true }),
    timeoutSeconds: 60,
    retryCount: 2,
    isEnabled: true,
    description: 'Stop services for rollback',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 6,
    apiName: 'Restore Database Backup',
    apiType: 'Rollback',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/database/restore',
    executionOrder: 2,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', backupId: '{{BACKUP_ID}}' }),
    timeoutSeconds: 300,
    retryCount: 1,
    isEnabled: true,
    description: 'Restore database from backup',
    createdDate: getDateString(-200),
    updatedDate: getDateString(-100),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    apiConfigurationId: 7,
    apiName: 'Revert to Previous Version',
    apiType: 'Rollback',
    httpMethod: 'POST',
    endpointURL: 'https://api.example.com/v1/rollback',
    executionOrder: 3,
    headers: JSON.stringify({ Authorization: 'Bearer YOUR_API_KEY_HERE', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '{{CLIENT_ID}}', targetVersion: '{{PREVIOUS_VERSION}}' }),
    timeoutSeconds: 600,
    retryCount: 1,
    isEnabled: true,
    description: 'Revert to previous stable version',
    createdDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
  },
];

// Mock Deployment Logs
export const mockDeploymentLogs: DeploymentLogResponse[] = [
  {
    deploymentLogId: 1,
    crfId: 3,
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    logType: 'Info',
    logMessage: 'Deployment started for CRF-2024-003',
    severity: 'Info',
    createdDate: getDateTimeString(-7, 0),
    createdBy: 1,
    createdByName: 'John Smith',
  },
  {
    deploymentLogId: 2,
    crfId: 3,
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    logType: 'Info',
    logMessage: 'Pre-deployment health check passed',
    severity: 'Info',
    createdDate: getDateTimeString(-7, 0.5),
    createdBy: 1,
    createdByName: 'System',
  },
  {
    deploymentLogId: 3,
    crfId: 3,
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    logType: 'Info',
    logMessage: 'Database backup completed successfully',
    severity: 'Info',
    createdDate: getDateTimeString(-7, 1),
    createdBy: 1,
    createdByName: 'System',
  },
  {
    deploymentLogId: 4,
    crfId: 3,
    clientId: 4,
    clientName: 'Enterprise Systems LLC',
    logType: 'Success',
    logMessage: 'Deployment completed successfully',
    severity: 'Info',
    createdDate: getDateTimeString(-7, 2),
    createdBy: 1,
    createdByName: 'System',
  },
  {
    deploymentLogId: 5,
    crfId: 5,
    clientId: 5,
    clientName: 'Digital Dynamics',
    logType: 'Info',
    logMessage: 'Deployment started for CRF-2023-099',
    severity: 'Info',
    createdDate: getDateTimeString(-30, 0),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
  },
  {
    deploymentLogId: 6,
    crfId: 5,
    clientId: 5,
    clientName: 'Digital Dynamics',
    logType: 'Error',
    logMessage: 'Database migration timeout error on table user_preferences',
    severity: 'Critical',
    createdDate: getDateTimeString(-30, 1),
    createdBy: 2,
    createdByName: 'System',
  },
  {
    deploymentLogId: 7,
    crfId: 5,
    clientId: 5,
    clientName: 'Digital Dynamics',
    logType: 'Warning',
    logMessage: 'Initiating rollback procedure',
    severity: 'High',
    createdDate: getDateTimeString(-30, 1.5),
    createdBy: 2,
    createdByName: 'System',
  },
  {
    deploymentLogId: 8,
    crfId: 5,
    clientId: 5,
    clientName: 'Digital Dynamics',
    logType: 'Info',
    logMessage: 'Rollback completed successfully',
    severity: 'Info',
    createdDate: getDateTimeString(-30, 2),
    createdBy: 2,
    createdByName: 'System',
  },
];

// Mock Error Notifications
export const mockErrorNotifications: ErrorNotificationResponse[] = [
  {
    errorNotificationId: 1,
    crfId: 5,
    clientId: 5,
    errorType: 'Database Migration Error',
    errorSource: 'DeploymentEngine',
    errorMessage: 'Timeout error on table user_preferences during migration',
    stackTrace: 'at DatabaseMigration.Execute() line 234\nat DeploymentEngine.RunMigrations() line 89',
    severity: 'Critical',
    isResolved: true,
    resolvedBy: 2,
    resolvedDate: getDateString(-29),
    resolutionNotes: 'Rolled back deployment and investigated timeout issue. Database performance tuning applied.',
    notificationSent: true,
    notificationSentDate: getDateString(-30),
    createdDate: getDateTimeString(-30, 1),
    crfNumber: 'CRF-2023-099',
    clientName: 'Digital Dynamics',
    resolvedByName: 'Sarah Johnson',
  },
  {
    errorNotificationId: 2,
    crfId: 4,
    clientId: 7,
    errorType: 'API Timeout',
    errorSource: 'HealthCheckAPI',
    errorMessage: 'Pre-deployment health check timed out after 30 seconds',
    stackTrace: 'at HealthCheckAPI.Execute() line 45\nat APIOrchestrator.RunAPIs() line 123',
    severity: 'High',
    isResolved: false,
    resolutionNotes: '',
    notificationSent: true,
    notificationSentDate: getDateString(-1),
    createdDate: getDateTimeString(-1, 0),
    crfNumber: 'CRF-2024-004',
    clientName: 'CloudFirst Solutions',
    resolvedByName: '',
  },
  {
    errorNotificationId: 3,
    errorType: 'Configuration Error',
    errorSource: 'SystemConfig',
    errorMessage: 'Missing API configuration for rollback step 3',
    stackTrace: 'at ConfigValidator.Validate() line 78',
    severity: 'Medium',
    isResolved: true,
    resolvedBy: 1,
    resolvedDate: getDateString(-10),
    resolutionNotes: 'Added missing rollback API configuration',
    notificationSent: false,
    createdDate: getDateTimeString(-11, 0),
    crfNumber: '',
    clientName: '',
    resolvedByName: 'John Smith',
  },
  {
    errorNotificationId: 4,
    crfId: 1,
    errorType: 'Validation Error',
    errorSource: 'CRFValidator',
    errorMessage: 'Client has customizations - cannot auto-deploy',
    stackTrace: 'at CRFValidator.ValidateClient() line 56',
    severity: 'Low',
    isResolved: false,
    resolutionNotes: '',
    notificationSent: true,
    notificationSentDate: getDateString(-3),
    createdDate: getDateTimeString(-3, 2),
    crfNumber: 'CRF-2024-001',
    clientName: '',
    resolvedByName: '',
  },
];

// Mock Deployment Queue
export const mockDeploymentQueue: DeploymentQueueResponse[] = [
  {
    deploymentQueueId: 1,
    crfId: 2,
    clientId: 3,
    queuedBy: 5,
    queuedDate: getDateString(-5),
    scheduledStartTime: getDateString(3),
    status: 'Queued',
    priority: 2,
    deploymentType: 'Automated',
    notes: 'Standard upgrade deployment',
    crfNumber: 'CRF-2024-002',
    crfTitle: 'Minor Version Upgrade - Innovate Solutions',
    clientName: 'Innovate Solutions',
    queuedByName: 'Robert Wilson',
    versionNumber: '3.2.1',
  },
  {
    deploymentQueueId: 2,
    crfId: 4,
    clientId: 2,
    queuedBy: 1,
    queuedDate: getDateString(-10),
    scheduledStartTime: getDateString(-1),
    actualStartTime: getDateString(-1),
    completedTime: getDateTimeString(-1, 2),
    status: 'Completed',
    priority: 2,
    deploymentType: 'Automated',
    notes: 'Bulk deployment - Part 1',
    crfNumber: 'CRF-2024-004',
    crfTitle: 'Bulk Update - Multiple Clients',
    clientName: 'Global Tech Industries',
    queuedByName: 'John Smith',
    versionNumber: '3.2.1',
  },
  {
    deploymentQueueId: 3,
    crfId: 4,
    clientId: 5,
    queuedBy: 1,
    queuedDate: getDateString(-10),
    scheduledStartTime: getDateString(-1),
    actualStartTime: getDateString(-1),
    completedTime: getDateTimeString(-1, 3),
    status: 'Completed',
    priority: 2,
    deploymentType: 'Automated',
    notes: 'Bulk deployment - Part 2',
    crfNumber: 'CRF-2024-004',
    crfTitle: 'Bulk Update - Multiple Clients',
    clientName: 'Digital Dynamics',
    queuedByName: 'John Smith',
    versionNumber: '3.2.1',
  },
  {
    deploymentQueueId: 4,
    crfId: 4,
    clientId: 7,
    queuedBy: 1,
    queuedDate: getDateString(-10),
    scheduledStartTime: getDateString(-1),
    actualStartTime: getDateString(-1),
    status: 'In Progress',
    priority: 2,
    deploymentType: 'Automated',
    notes: 'Bulk deployment - Part 3',
    crfNumber: 'CRF-2024-004',
    crfTitle: 'Bulk Update - Multiple Clients',
    clientName: 'CloudFirst Solutions',
    queuedByName: 'John Smith',
    versionNumber: '3.2.1',
  },
  {
    deploymentQueueId: 5,
    crfId: 1,
    clientId: 1,
    queuedBy: 2,
    queuedDate: getDateString(-3),
    scheduledStartTime: getDateString(5),
    status: 'Queued',
    priority: 1,
    deploymentType: 'Manual',
    notes: 'Manual deployment required - client has customizations',
    crfNumber: 'CRF-2024-001',
    crfTitle: 'Security Update for Acme Corporation',
    clientName: 'Acme Corporation',
    queuedByName: 'Sarah Johnson',
    versionNumber: '3.2.1',
  },
];

// Mock Notifications
export const mockNotifications: NotificationResponse[] = [
  {
    notificationId: 1,
    userId: 1,
    title: 'CRF Approval Required',
    message: 'CRF-2024-001 requires your approval',
    type: 'approval_request',
    priority: 'high',
    isRead: false,
    relatedEntityType: 'CRF',
    relatedEntityId: 1,
    actionUrl: '/crf/workflow',
    createdAt: getDateTimeString(-3),
    expiresAt: getDateTimeString(7),
  },
  {
    notificationId: 2,
    userId: 2,
    title: 'Deployment Failed',
    message: 'Deployment for CRF-2023-099 failed - rollback initiated',
    type: 'deployment_failure',
    priority: 'critical',
    isRead: true,
    relatedEntityType: 'CRF',
    relatedEntityId: 5,
    actionUrl: '/deployment-logs',
    createdAt: getDateTimeString(-30),
    readAt: getDateTimeString(-29),
    expiresAt: getDateTimeString(-20),
  },
  {
    notificationId: 3,
    userId: 1,
    title: 'Deployment Successful',
    message: 'CRF-2024-003 deployed successfully to Enterprise Systems LLC',
    type: 'deployment_success',
    priority: 'medium',
    isRead: true,
    relatedEntityType: 'CRF',
    relatedEntityId: 3,
    actionUrl: '/deployment-logs',
    createdAt: getDateTimeString(-7),
    readAt: getDateTimeString(-7),
  },
  {
    notificationId: 4,
    userId: 5,
    title: 'CRF Approved',
    message: 'Your CRF-2024-002 has been approved',
    type: 'approval_granted',
    priority: 'medium',
    isRead: false,
    relatedEntityType: 'CRF',
    relatedEntityId: 2,
    actionUrl: '/crf/workflow',
    createdAt: getDateTimeString(-1),
    expiresAt: getDateTimeString(6),
  },
  {
    notificationId: 5,
    userId: 3,
    title: 'Version Update Available',
    message: 'New version 3.2.1 is available for your environment',
    type: 'version_release',
    priority: 'low',
    isRead: false,
    relatedEntityType: 'Version',
    relatedEntityId: 1,
    actionUrl: '/versions',
    createdAt: getDateTimeString(-30),
    expiresAt: getDateTimeString(30),
  },
];

// Mock Audit Logs
export const mockAuditLogs: AuditLogResponse[] = [
  {
    auditLogId: 1,
    userId: 1,
    username: 'devops_admin',
    action: 'CREATE',
    entityType: 'CRF',
    entityId: 1,
    details: 'Created CRF-2024-001',
    oldValue: null,
    newValue: JSON.stringify({ crfNumber: 'CRF-2024-001', title: 'Security Update for Acme Corporation' }),
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-3),
  },
  {
    auditLogId: 2,
    userId: 2,
    username: 'delivery_lead',
    action: 'UPDATE',
    entityType: 'CRF',
    entityId: 2,
    details: 'Approved CRF-2024-002',
    oldValue: JSON.stringify({ status: 'Pending' }),
    newValue: JSON.stringify({ status: 'Approved' }),
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-2),
  },
  {
    auditLogId: 3,
    userId: 1,
    username: 'devops_admin',
    action: 'CREATE',
    entityType: 'Client',
    entityId: 8,
    details: 'Created client DataCore Systems',
    oldValue: null,
    newValue: JSON.stringify({ clientName: 'DataCore Systems', status: 'Active' }),
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-500),
  },
  {
    auditLogId: 4,
    userId: 1,
    username: 'devops_admin',
    action: 'CREATE',
    entityType: 'Version',
    entityId: 1,
    details: 'Created version 3.2.1',
    oldValue: null,
    newValue: JSON.stringify({ versionNumber: '3.2.1', versionName: 'Winter 2024 Release' }),
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-35),
  },
  {
    auditLogId: 5,
    userId: 2,
    username: 'delivery_lead',
    action: 'UPDATE',
    entityType: 'Client',
    entityId: 1,
    details: 'Updated client Acme Corporation customization flag',
    oldValue: JSON.stringify({ hasCustomizations: false }),
    newValue: JSON.stringify({ hasCustomizations: true }),
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-100),
  },
  {
    auditLogId: 6,
    userId: 1,
    username: 'devops_admin',
    action: 'CREATE',
    entityType: 'APIConfiguration',
    entityId: 1,
    details: 'Created API configuration: Pre-deployment Health Check',
    oldValue: null,
    newValue: JSON.stringify({ apiName: 'Pre-deployment Health Check', apiType: 'Deployment' }),
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-200),
  },
  {
    auditLogId: 7,
    userId: 4,
    username: 'devops_engineer',
    action: 'UPDATE',
    entityType: 'WorkflowStep',
    entityId: 5,
    details: 'Disabled workflow step: Change Advisory Board',
    oldValue: JSON.stringify({ isActive: true }),
    newValue: JSON.stringify({ isActive: false }),
    ipAddress: '192.168.1.102',
    userAgent: 'Mozilla/5.0',
    timestamp: getDateTimeString(-50),
  },
];

// Mock Bulk Operations
export const mockBulkOperations: BulkOperationResponse[] = [
  {
    bulkOperationId: 1,
    operationType: 'BULK_UPDATE_CLIENTS',
    initiatedBy: 1,
    initiatedByName: 'John Smith',
    initiatedAt: getDateTimeString(-10),
    completedAt: getDateTimeString(-10, 0.5),
    status: 'Completed',
    totalItems: 3,
    processedItems: 3,
    successfulItems: 2,
    failedItems: 1,
    resultData: JSON.stringify({ successful: [2, 5], failed: [7] }),
    inputData: JSON.stringify({ clientIds: [2, 5, 7], newVersion: '3.2.1' }),
  },
  {
    bulkOperationId: 2,
    operationType: 'BULK_CREATE_CRFS',
    initiatedBy: 2,
    initiatedByName: 'Sarah Johnson',
    initiatedAt: getDateTimeString(-20),
    completedAt: getDateTimeString(-20, 0.3),
    status: 'Completed',
    totalItems: 5,
    processedItems: 5,
    successfulItems: 5,
    failedItems: 0,
    resultData: JSON.stringify({ crfIds: [1, 2, 3, 4, 5] }),
    inputData: JSON.stringify({ count: 5 }),
  },
  {
    bulkOperationId: 3,
    operationType: 'BULK_UPDATE_CLIENTS',
    initiatedBy: 1,
    initiatedByName: 'John Smith',
    initiatedAt: getDateTimeString(-1),
    status: 'In Progress',
    totalItems: 10,
    processedItems: 7,
    successfulItems: 7,
    failedItems: 0,
    inputData: JSON.stringify({ clientIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], newStatus: 'Active' }),
  },
];

// Mock CRF Templates
export const mockCRFTemplates: CRFTemplateResponse[] = [
  {
    crfTemplateId: 1,
    templateName: 'Standard Version Update',
    description: 'Standard template for version updates',
    crfNumberPrefix: 'CRF',
    defaultTitle: 'Version Update',
    defaultDescription: 'Standard version update deployment',
    defaultPriority: 'Medium',
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-400),
    usageCount: 15,
  },
  {
    crfTemplateId: 2,
    templateName: 'Security Patch',
    description: 'Template for security patch deployments',
    crfNumberPrefix: 'SEC',
    defaultTitle: 'Security Patch Deployment',
    defaultDescription: 'Critical security patch deployment',
    defaultPriority: 'High',
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-350),
    updatedDate: getDateString(-100),
    usageCount: 8,
  },
  {
    crfTemplateId: 3,
    templateName: 'Emergency Hotfix',
    description: 'Template for emergency hotfix deployments',
    crfNumberPrefix: 'HOTFIX',
    defaultTitle: 'Emergency Hotfix',
    defaultDescription: 'Emergency hotfix deployment - immediate action required',
    defaultPriority: 'Critical',
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-200),
    usageCount: 3,
  },
];

// Mock API Execution Logs
export const mockAPIExecutionLogs: APIExecutionLogResponse[] = [
  {
    apiExecutionLogId: 1,
    crfId: 3,
    clientId: 4,
    apiConfigurationId: 1,
    executionType: 'Deployment',
    requestURL: 'https://api.example.com/v1/health/check',
    requestHeaders: JSON.stringify({ Authorization: 'Bearer ***', 'Content-Type': 'application/json' }),
    requestBody: '',
    responseStatusCode: 200,
    responseBody: JSON.stringify({ status: 'healthy', uptime: 99.98 }),
    executionStartTime: getDateTimeString(-7, 0),
    executionEndTime: getDateTimeString(-7, 0.01),
    durationMs: 450,
    status: 'Success',
    errorMessage: '',
    retryAttempt: 0,
    apiName: 'Pre-deployment Health Check',
    clientName: 'Enterprise Systems LLC',
    crfNumber: 'CRF-2024-003',
  },
  {
    apiExecutionLogId: 2,
    crfId: 3,
    clientId: 4,
    apiConfigurationId: 2,
    executionType: 'Deployment',
    requestURL: 'https://api.example.com/v1/database/backup',
    requestHeaders: JSON.stringify({ Authorization: 'Bearer ***', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '4', backupType: 'full' }),
    responseStatusCode: 200,
    responseBody: JSON.stringify({ backupId: 'backup-123', status: 'completed' }),
    executionStartTime: getDateTimeString(-7, 0.5),
    executionEndTime: getDateTimeString(-7, 0.7),
    durationMs: 12500,
    status: 'Success',
    errorMessage: '',
    retryAttempt: 0,
    apiName: 'Create Database Backup',
    clientName: 'Enterprise Systems LLC',
    crfNumber: 'CRF-2024-003',
  },
  {
    apiExecutionLogId: 3,
    crfId: 5,
    clientId: 5,
    apiConfigurationId: 1,
    executionType: 'Deployment',
    requestURL: 'https://api.example.com/v1/health/check',
    requestHeaders: JSON.stringify({ Authorization: 'Bearer ***', 'Content-Type': 'application/json' }),
    requestBody: '',
    responseStatusCode: 200,
    responseBody: JSON.stringify({ status: 'healthy' }),
    executionStartTime: getDateTimeString(-30, 0),
    executionEndTime: getDateTimeString(-30, 0.01),
    durationMs: 520,
    status: 'Success',
    errorMessage: '',
    retryAttempt: 0,
    apiName: 'Pre-deployment Health Check',
    clientName: 'Digital Dynamics',
    crfNumber: 'CRF-2023-099',
  },
  {
    apiExecutionLogId: 4,
    crfId: 5,
    clientId: 5,
    apiConfigurationId: 3,
    executionType: 'Deployment',
    requestURL: 'https://api.example.com/v1/deploy',
    requestHeaders: JSON.stringify({ Authorization: 'Bearer ***', 'Content-Type': 'application/json' }),
    requestBody: JSON.stringify({ clientId: '5', version: '3.2.0', environment: 'Production' }),
    responseStatusCode: 500,
    responseBody: JSON.stringify({ error: 'Database migration timeout' }),
    executionStartTime: getDateTimeString(-30, 0.5),
    executionEndTime: getDateTimeString(-30, 1),
    durationMs: 60000,
    status: 'Failed',
    errorMessage: 'Timeout error on table user_preferences',
    retryAttempt: 1,
    apiName: 'Deploy New Version',
    clientName: 'Digital Dynamics',
    crfNumber: 'CRF-2023-099',
  },
  {
    apiExecutionLogId: 5,
    crfId: 4,
    clientId: 7,
    apiConfigurationId: 1,
    executionType: 'Deployment',
    requestURL: 'https://api.example.com/v1/health/check',
    requestHeaders: JSON.stringify({ Authorization: 'Bearer ***', 'Content-Type': 'application/json' }),
    requestBody: '',
    responseStatusCode: 0,
    responseBody: '',
    executionStartTime: getDateTimeString(-1, 0),
    executionEndTime: getDateTimeString(-1, 0.5),
    durationMs: 30000,
    status: 'Failed',
    errorMessage: 'Request timeout after 30 seconds',
    retryAttempt: 2,
    apiName: 'Pre-deployment Health Check',
    clientName: 'CloudFirst Solutions',
    crfNumber: 'CRF-2024-004',
  },
];

// Export mock data store for runtime modifications
export class MockDataStore {
  users = [...mockUsers];
  userDtos = [...mockUserDtos];
  roles = [...mockRoles];
  versions = [...mockVersions];
  clients = [...mockClients];
  clientVersionHistory = [...mockClientVersionHistory];
  workflowSteps = [...mockWorkflowSteps];
  crfs = [...mockCRFs];
  crfClients = [...mockCRFClients];
  crfApprovals = [...mockCRFApprovals];
  apiConfigurations = [...mockAPIConfigurations];
  deploymentLogs = [...mockDeploymentLogs];
  errorNotifications = [...mockErrorNotifications];
  deploymentQueue = [...mockDeploymentQueue];
  notifications = [...mockNotifications];
  auditLogs = [...mockAuditLogs];
  bulkOperations = [...mockBulkOperations];
  crfTemplates = [...mockCRFTemplates];
  apiExecutionLogs = [...mockAPIExecutionLogs];

  // Helper to get next ID
  getNextId(array: any[]): number {
    return Math.max(...array.map(item => item[Object.keys(item)[0]]), 0) + 1;
  }

  // Helper to create audit log
  createAuditLog(userId: number, username: string, action: string, entityType: string, entityId: number | null, details: string, oldValue?: any, newValue?: any) {
    const auditLog: AuditLogResponse = {
      auditLogId: this.getNextId(this.auditLogs),
      userId,
      username,
      action,
      entityType,
      entityId: entityId || undefined,
      details,
      oldValue: oldValue ? JSON.stringify(oldValue) : undefined,
      newValue: newValue ? JSON.stringify(newValue) : undefined,
      ipAddress: '192.168.1.100',
      userAgent: 'Mozilla/5.0',
      timestamp: new Date().toISOString(),
    };
    this.auditLogs.unshift(auditLog);
  }

  reset() {
    this.users = [...mockUsers];
    this.userDtos = [...mockUserDtos];
    this.roles = [...mockRoles];
    this.versions = [...mockVersions];
    this.clients = [...mockClients];
    this.clientVersionHistory = [...mockClientVersionHistory];
    this.workflowSteps = [...mockWorkflowSteps];
    this.crfs = [...mockCRFs];
    this.crfClients = [...mockCRFClients];
    this.crfApprovals = [...mockCRFApprovals];
    this.apiConfigurations = [...mockAPIConfigurations];
    this.deploymentLogs = [...mockDeploymentLogs];
    this.errorNotifications = [...mockErrorNotifications];
    this.deploymentQueue = [...mockDeploymentQueue];
    this.notifications = [...mockNotifications];
    this.auditLogs = [...mockAuditLogs];
    this.bulkOperations = [...mockBulkOperations];
    this.crfTemplates = [...mockCRFTemplates];
    this.apiExecutionLogs = [...mockAPIExecutionLogs];
  }
}

export const mockDataStore = new MockDataStore();
