// EXPANDED MOCK DATA - Part 1
// This file contains additional mock data to be integrated into mockDataProvider.ts

import type {
  UserResponse,
  UserDto,
  VersionResponse,
  ClientResponse,
  ClientVersionHistory,
  CRFResponse,
  CRFClientResponse,
  CRFApprovalResponse,
  DeploymentLogResponse,
  ErrorNotificationResponse,
  NotificationResponse,
  AuditLogResponse,
  BulkOperationResponse,
  DeploymentQueueResponse,
  CRFTemplateResponse,
  APIExecutionLogResponse,
} from '../services/api';

// Helper to generate dates
const getDateString = (daysOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

const getDateTimeString = (daysOffset: number = 0, hoursOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(date.getHours() + hoursOffset);
  return date.toISOString();
};

// ADDITIONAL USERS (expanding from 7 to 25 users)
export const additionalUsers: UserResponse[] = [
  {
    userId: 8,
    username: 'devops_senior',
    email: 'senior@devops.com',
    firstName: 'Marcus',
    lastName: 'Thompson',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-320),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 9,
    username: 'delivery_manager',
    email: 'manager@delivery.com',
    firstName: 'Amanda',
    lastName: 'Rodriguez',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-280),
    lastLoginDate: getDateTimeString(-2),
  },
  {
    userId: 10,
    username: 'client_techstart',
    email: 'ops@techstart.com',
    firstName: 'Kevin',
    lastName: 'Brown',
    company: 'TechStart Inc',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-120),
    lastLoginDate: getDateTimeString(-15),
  },
  {
    userId: 11,
    username: 'client_datacore',
    email: 'admin@datacore.com',
    firstName: 'Sandra',
    lastName: 'Lee',
    company: 'DataCore Systems',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-500),
    lastLoginDate: getDateTimeString(-4),
  },
  {
    userId: 12,
    username: 'devops_junior',
    email: 'junior@devops.com',
    firstName: 'Tyler',
    lastName: 'Anderson',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-90),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 13,
    username: 'delivery_specialist',
    email: 'specialist@delivery.com',
    firstName: 'Nicole',
    lastName: 'White',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-200),
    lastLoginDate: getDateTimeString(-3),
  },
  {
    userId: 14,
    username: 'client_cloudnative',
    email: 'it@cloudnative.com',
    firstName: 'James',
    lastName: 'Miller',
    company: 'CloudNative Corp',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-400),
    lastLoginDate: getDateTimeString(-2),
  },
  {
    userId: 15,
    username: 'client_fintech',
    email: 'ops@fintechsolutions.com',
    firstName: 'Patricia',
    lastName: 'Garcia',
    company: 'FinTech Solutions',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-350),
    lastLoginDate: getDateTimeString(-6),
  },
  {
    userId: 16,
    username: 'client_healthtech',
    email: 'admin@healthtech.com',
    firstName: 'Christopher',
    lastName: 'Martinez',
    company: 'HealthTech Systems',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-280),
    lastLoginDate: getDateTimeString(-8),
  },
  {
    userId: 17,
    username: 'client_ecommerce',
    email: 'it@ecommercepro.com',
    firstName: 'Jessica',
    lastName: 'Taylor',
    company: 'E-Commerce Pro',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-220),
    lastLoginDate: getDateTimeString(-5),
  },
  {
    userId: 18,
    username: 'client_manufacturing',
    email: 'tech@manufact.com',
    firstName: 'Daniel',
    lastName: 'Thomas',
    company: 'Manufacturing Tech Inc',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-310),
    lastLoginDate: getDateTimeString(-10),
  },
  {
    userId: 19,
    username: 'delivery_coordinator',
    email: 'coordinator@delivery.com',
    firstName: 'Michelle',
    lastName: 'Jackson',
    company: 'Delivery Team',
    roles: 'Delivery',
    isActive: true,
    createdDate: getDateString(-140),
    lastLoginDate: getDateTimeString(-1),
  },
  {
    userId: 20,
    username: 'client_logistics',
    email: 'systems@logisticsplus.com',
    firstName: 'Brian',
    lastName: 'Harris',
    company: 'Logistics Plus',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-260),
    lastLoginDate: getDateTimeString(-12),
  },
  {
    userId: 21,
    username: 'client_retail',
    email: 'it@retailchain.com',
    firstName: 'Angela',
    lastName: 'Clark',
    company: 'Retail Chain Solutions',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-190),
    lastLoginDate: getDateTimeString(-7),
  },
  {
    userId: 22,
    username: 'client_education',
    email: 'admin@edutech.com',
    firstName: 'Steven',
    lastName: 'Lewis',
    company: 'EduTech Platform',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-230),
    lastLoginDate: getDateTimeString(-14),
  },
  {
    userId: 23,
    username: 'client_insurance',
    email: 'ops@insurancetech.com',
    firstName: 'Laura',
    lastName: 'Walker',
    company: 'InsuranceTech Group',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-340),
    lastLoginDate: getDateTimeString(-9),
  },
  {
    userId: 24,
    username: 'client_telecom',
    email: 'tech@telecomcorp.com',
    firstName: 'Ryan',
    lastName: 'Hall',
    company: 'Telecom Corporation',
    roles: 'Client',
    isActive: true,
    createdDate: getDateString(-270),
    lastLoginDate: getDateTimeString(-11),
  },
  {
    userId: 25,
    username: 'devops_architect',
    email: 'architect@devops.com',
    firstName: 'Monica',
    lastName: 'Allen',
    company: 'DevOps Team',
    roles: 'DevOps',
    isActive: true,
    createdDate: getDateString(-420),
    lastLoginDate: getDateTimeString(0),
  },
];

// ADDITIONAL VERSIONS (expanding from 5 to 15 versions)
export const additionalVersions: VersionResponse[] = [
  {
    versionId: 6,
    versionNumber: '3.0.7',
    versionName: 'Legacy Patch 7',
    releaseDate: getDateString(-330),
    description: 'Security patches for legacy version',
    releaseNotes: 'Critical security fixes, performance improvements',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-340),
    updatedDate: getDateString(-330),
    clientCount: 1,
  },
  {
    versionId: 7,
    versionNumber: '3.0.5',
    versionName: 'Legacy Patch 5',
    releaseDate: getDateString(-360),
    description: 'Bug fixes for legacy version',
    releaseNotes: 'Various bug fixes and stability improvements',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-370),
    updatedDate: getDateString(-360),
    clientCount: 0,
  },
  {
    versionId: 8,
    versionNumber: '2.9.0',
    versionName: 'End of Life Release',
    releaseDate: getDateString(-400),
    description: 'Final 2.x series release',
    releaseNotes: 'End of life announcement, upgrade path to 3.x',
    isMajorRelease: true,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-410),
    clientCount: 0,
  },
  {
    versionId: 9,
    versionNumber: '3.1.8',
    versionName: 'Summer 2024 Hotfix',
    releaseDate: getDateString(-120),
    description: 'Critical hotfix for 3.1.5',
    releaseNotes: 'Fixed critical authentication bug, improved session management',
    isMajorRelease: false,
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-125),
    updatedDate: getDateString(-120),
    clientCount: 12,
  },
  {
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    releaseDate: getDateString(-10),
    description: 'Latest hotfix with performance improvements',
    releaseNotes: 'Performance optimization, memory leak fixes, UI improvements',
    isMajorRelease: false,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-15),
    updatedDate: getDateString(-10),
    clientCount: 3,
  },
  {
    versionId: 11,
    versionNumber: '3.0.3',
    versionName: 'Legacy Patch 3',
    releaseDate: getDateString(-420),
    description: 'Early legacy patch',
    releaseNotes: 'UI fixes, minor security updates',
    isMajorRelease: false,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-430),
    clientCount: 0,
  },
  {
    versionId: 12,
    versionNumber: '3.1.3',
    versionName: 'Spring 2024 Patch',
    releaseDate: getDateString(-180),
    description: 'Bug fixes for Spring release',
    releaseNotes: 'Fixed login issues, improved data export functionality',
    isMajorRelease: false,
    isActive: true,
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-190),
    updatedDate: getDateString(-180),
    clientCount: 8,
  },
  {
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    releaseDate: getDateString(30),
    description: 'Upcoming release with AI features',
    releaseNotes: 'AI-powered analytics, enhanced reporting, new integrations',
    isMajorRelease: false,
    isActive: true,
    createdBy: 25,
    createdByName: 'Monica Allen',
    createdDate: getDateString(10),
    updatedDate: getDateString(15),
    clientCount: 0,
  },
  {
    versionId: 14,
    versionNumber: '3.1.2',
    versionName: 'Spring 2024 Hotfix 2',
    releaseDate: getDateString(-195),
    description: 'Emergency hotfix',
    releaseNotes: 'Critical security vulnerability patch',
    isMajorRelease: false,
    isActive: true,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-196),
    updatedDate: getDateString(-195),
    clientCount: 5,
  },
  {
    versionId: 15,
    versionNumber: '3.0.0',
    versionName: 'Major Release 3.0',
    releaseDate: getDateString(-450),
    description: 'Major version 3.0 initial release',
    releaseNotes: 'Complete platform redesign, new architecture, enhanced security',
    isMajorRelease: true,
    isActive: false,
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-460),
    clientCount: 0,
  },
];

// ADDITIONAL CLIENTS (expanding from 8 to 30 clients)
export const additionalClients: ClientResponse[] = [
  {
    clientId: 9,
    clientName: 'CloudNative Corp',
    contactEmail: 'it@cloudnative.com',
    contactPerson: 'James Miller',
    phone: '+1-555-0109',
    address: '111 Cloud Way, Portland, OR 97201',
    currentVersionId: 1,
    currentVersion: '3.2.1',
    currentVersionName: 'Winter 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-20),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-400),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 10,
    clientName: 'FinTech Solutions',
    contactEmail: 'ops@fintechsolutions.com',
    contactPerson: 'Patricia Garcia',
    phone: '+1-555-0110',
    address: '222 Finance St, Charlotte, NC 28201',
    currentVersionId: 2,
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-75),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-350),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 11,
    clientName: 'HealthTech Systems',
    contactEmail: 'admin@healthtech.com',
    contactPerson: 'Christopher Martinez',
    phone: '+1-555-0111',
    address: '333 Medical Dr, Houston, TX 77001',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-140),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-280),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 12,
    clientName: 'E-Commerce Pro',
    contactEmail: 'it@ecommercepro.com',
    contactPerson: 'Jessica Taylor',
    phone: '+1-555-0112',
    address: '444 Retail Blvd, Los Angeles, CA 90001',
    currentVersionId: 10,
    currentVersion: '3.2.2',
    currentVersionName: 'Winter 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-8),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-220),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 13,
    clientName: 'Manufacturing Tech Inc',
    contactEmail: 'tech@manufact.com',
    contactPerson: 'Daniel Thomas',
    phone: '+1-555-0113',
    address: '555 Industry Ave, Detroit, MI 48201',
    currentVersionId: 4,
    currentVersion: '3.1.0',
    currentVersionName: 'Spring 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-200),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-310),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 14,
    clientName: 'Logistics Plus',
    contactEmail: 'systems@logisticsplus.com',
    contactPerson: 'Brian Harris',
    phone: '+1-555-0114',
    address: '666 Transport Way, Memphis, TN 38101',
    currentVersionId: 9,
    currentVersion: '3.1.8',
    currentVersionName: 'Summer 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-115),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-260),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 15,
    clientName: 'Retail Chain Solutions',
    contactEmail: 'it@retailchain.com',
    contactPerson: 'Angela Clark',
    phone: '+1-555-0115',
    address: '777 Commerce St, Atlanta, GA 30301',
    currentVersionId: 1,
    currentVersion: '3.2.1',
    currentVersionName: 'Winter 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-22),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-190),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 16,
    clientName: 'EduTech Platform',
    contactEmail: 'admin@edutech.com',
    contactPerson: 'Steven Lewis',
    phone: '+1-555-0116',
    address: '888 Campus Dr, Boston, MA 02115',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-148),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-230),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 17,
    clientName: 'InsuranceTech Group',
    contactEmail: 'ops@insurancetech.com',
    contactPerson: 'Laura Walker',
    phone: '+1-555-0117',
    address: '999 Policy Plaza, Hartford, CT 06101',
    currentVersionId: 2,
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-82),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-340),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 18,
    clientName: 'Telecom Corporation',
    contactEmail: 'tech@telecomcorp.com',
    contactPerson: 'Ryan Hall',
    phone: '+1-555-0118',
    address: '1010 Network Blvd, Dallas, TX 75201',
    currentVersionId: 9,
    currentVersion: '3.1.8',
    currentVersionName: 'Summer 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-118),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-270),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 19,
    clientName: 'Media & Entertainment Co',
    contactEmail: 'it@mediaent.com',
    contactPerson: 'Victoria Adams',
    phone: '+1-555-0119',
    address: '1111 Studio Way, Los Angeles, CA 90028',
    currentVersionId: 10,
    currentVersion: '3.2.2',
    currentVersionName: 'Winter 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-9),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-160),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 20,
    clientName: 'Energy Systems Inc',
    contactEmail: 'admin@energysys.com',
    contactPerson: 'Michael Scott',
    phone: '+1-555-0120',
    address: '1212 Power Ave, Houston, TX 77002',
    currentVersionId: 4,
    currentVersion: '3.1.0',
    currentVersionName: 'Spring 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-208),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-380),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 21,
    clientName: 'Government Services Corp',
    contactEmail: 'tech@govservices.com',
    contactPerson: 'Robert Johnson',
    phone: '+1-555-0121',
    address: '1313 Federal Way, Washington, DC 20001',
    currentVersionId: 6,
    currentVersion: '3.0.7',
    currentVersionName: 'Legacy Patch 7',
    status: 'Active',
    lastUpdateDate: getDateString(-325),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-480),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 22,
    clientName: 'Hospitality Solutions',
    contactEmail: 'ops@hospitalitysol.com',
    contactPerson: 'Jennifer Lopez',
    phone: '+1-555-0122',
    address: '1414 Hotel Blvd, Las Vegas, NV 89101',
    currentVersionId: 1,
    currentVersion: '3.2.1',
    currentVersionName: 'Winter 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-27),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-175),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 23,
    clientName: 'Real Estate Tech',
    contactEmail: 'it@realestatetech.com',
    contactPerson: 'Thomas Anderson',
    phone: '+1-555-0123',
    address: '1515 Property St, San Diego, CA 92101',
    currentVersionId: 12,
    currentVersion: '3.1.3',
    currentVersionName: 'Spring 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-175),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-210),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 24,
    clientName: 'Aerospace Systems Ltd',
    contactEmail: 'admin@aerospace.com',
    contactPerson: 'Elizabeth Turner',
    phone: '+1-555-0124',
    address: '1616 Aerospace Pkwy, Seattle, WA 98108',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-145),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-390),
    isActive: true,
    hasCustomizations: true, // Cannot auto-update
  },
  {
    clientId: 25,
    clientName: 'Agriculture Tech Co',
    contactEmail: 'tech@agritech.com',
    contactPerson: 'William Brown',
    phone: '+1-555-0125',
    address: '1717 Farm Road, Des Moines, IA 50301',
    currentVersionId: 9,
    currentVersion: '3.1.8',
    currentVersionName: 'Summer 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-119),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-240),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 26,
    clientName: 'Pharmaceutical Systems',
    contactEmail: 'ops@pharmasys.com',
    contactPerson: 'Margaret Davis',
    phone: '+1-555-0126',
    address: '1818 Medical Center Dr, Philadelphia, PA 19101',
    currentVersionId: 2,
    currentVersion: '3.2.0',
    currentVersionName: 'Fall 2024 Release',
    status: 'Active',
    lastUpdateDate: getDateString(-86),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-330),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 27,
    clientName: 'Automotive Tech Group',
    contactEmail: 'it@autotech.com',
    contactPerson: 'Joseph Wilson',
    phone: '+1-555-0127',
    address: '1919 Motor Way, Detroit, MI 48226',
    currentVersionId: 14,
    currentVersion: '3.1.2',
    currentVersionName: 'Spring 2024 Hotfix 2',
    status: 'Active',
    lastUpdateDate: getDateString(-193),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-360),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 28,
    clientName: 'Gaming Platform Inc',
    contactEmail: 'admin@gamingplatform.com',
    contactPerson: 'Sarah Connor',
    phone: '+1-555-0128',
    address: '2020 Game St, San Francisco, CA 94103',
    currentVersionId: 10,
    currentVersion: '3.2.2',
    currentVersionName: 'Winter 2024 Hotfix',
    status: 'Active',
    lastUpdateDate: getDateString(-7),
    createdBy: 4,
    createdByName: 'Emily Davis',
    createdDate: getDateString(-140),
    isActive: true,
    hasCustomizations: false,
  },
  {
    clientId: 29,
    clientName: 'Legal Tech Solutions',
    contactEmail: 'tech@legaltech.com',
    contactPerson: 'Andrew Mitchell',
    phone: '+1-555-0129',
    address: '2121 Justice Ave, New York, NY 10004',
    currentVersionId: 3,
    currentVersion: '3.1.5',
    currentVersionName: 'Summer 2024 Patch',
    status: 'Inactive',
    lastUpdateDate: getDateString(-152),
    createdBy: 2,
    createdByName: 'Sarah Johnson',
    createdDate: getDateString(-250),
    isActive: false,
    hasCustomizations: false,
  },
  {
    clientId: 30,
    clientName: 'Construction Management Pro',
    contactEmail: 'ops@constructionpro.com',
    contactPerson: 'Barbara Moore',
    phone: '+1-555-0130',
    address: '2222 Builder Blvd, Phoenix, AZ 85001',
    currentVersionId: 12,
    currentVersion: '3.1.3',
    currentVersionName: 'Spring 2024 Patch',
    status: 'Active',
    lastUpdateDate: getDateString(-178),
    createdBy: 1,
    createdByName: 'John Smith',
    createdDate: getDateString(-290),
    isActive: true,
    hasCustomizations: false,
  },
];

// Export combined lists for easy integration
export const expandedMockData = {
  users: additionalUsers,
  versions: additionalVersions,
  clients: additionalClients,
};
