// EXPANDED MOCK DATA - Part 2: Additional CRFs, Notifications, Audit Logs, and More
// This file contains comprehensive expansions for all data types

import type {
  CRFResponse,
  CRFClientResponse,
  CRFApprovalResponse,
  DeploymentLogResponse,
  ClientVersionHistory,
  ErrorNotificationResponse,
  NotificationResponse,
  AuditLogResponse,
  BulkOperationResponse,
  DeploymentQueueResponse,
  CRFTemplateResponse,
  APIExecutionLogResponse,
} from '../services/api';

// Helper to generate dates
const getDateString = (daysOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

const getDateTimeString = (daysOffset: number = 0, hoursOffset: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(date.getHours() + hoursOffset);
  return date.toISOString();
};

// ADDITIONAL CRFs (IDs 7-40)
export const additionalCRFs: CRFResponse[] = [
  {
    crfId: 7,
    crfNumber: 'CRF-2024-006',
    title: 'Emergency Security Patch - FinTech Solutions',
    description: 'Critical security vulnerability fix',
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    requestedBy: 8,
    requestedByName: 'Marcus Thompson',
    status: 'Approved',
    priority: 'Critical',
    scheduledDeploymentDate: getDateString(1),
    createdDate: getDateString(-4),
    updatedDate: getDateString(-1),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 8,
    crfNumber: 'CRF-2024-007',
    title: 'Routine Maintenance - Healthcare Clients',
    description: 'Standard quarterly update for healthcare sector',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 9,
    requestedByName: 'Amanda Rodriguez',
    status: 'Pending',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(8),
    createdDate: getDateString(-6),
    clientCount: 2,
    successfulDeployments: 0,
  },
  {
    crfId: 9,
    crfNumber: 'CRF-2024-008',
    title: 'UI Enhancement - Retail Sector',
    description: 'New dashboard features for retail clients',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 13,
    requestedByName: 'Nicole White',
    status: 'Approved',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(15),
    createdDate: getDateString(-8),
    updatedDate: getDateString(-2),
    clientCount: 3,
    successfulDeployments: 0,
  },
  {
    crfId: 10,
    crfNumber: 'CRF-2024-009',
    title: 'Performance Optimization - E-Commerce',
    description: 'Database and API performance improvements',
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-5),
    actualDeploymentDate: getDateString(-5),
    createdDate: getDateString(-12),
    updatedDate: getDateString(-5),
    completedDate: getDateString(-5),
    clientCount: 2,
    successfulDeployments: 2,
  },
  {
    crfId: 11,
    crfNumber: 'CRF-2024-010',
    title: 'New Feature Rollout - Logistics Platform',
    description: 'Advanced tracking and reporting features',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(0),
    actualDeploymentDate: getDateString(0),
    createdDate: getDateString(-15),
    updatedDate: getDateString(0),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 12,
    crfNumber: 'CRF-2024-011',
    title: 'Compliance Update - Insurance Sector',
    description: 'Regulatory compliance updates for insurance industry',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Rejected',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-15),
    createdDate: getDateString(-20),
    updatedDate: getDateString(-15),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 13,
    crfNumber: 'CRF-2023-100',
    title: 'Year-End Rollup - Manufacturing',
    description: 'Consolidated updates for manufacturing clients',
    versionId: 9,
    versionNumber: '3.1.8',
    versionName: 'Summer 2024 Hotfix',
    requestedBy: 4,
    requestedByName: 'Emily Davis',
    status: 'Completed',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-60),
    actualDeploymentDate: getDateString(-60),
    createdDate: getDateString(-70),
    updatedDate: getDateString(-60),
    completedDate: getDateString(-60),
    clientCount: 2,
    successfulDeployments: 2,
  },
  {
    crfId: 14,
    crfNumber: 'CRF-2024-012',
    title: 'Integration Update - Telecom Systems',
    description: 'Third-party API integration enhancements',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 19,
    requestedByName: 'Michelle Jackson',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(12),
    createdDate: getDateString(-7),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 15,
    crfNumber: 'CRF-2024-013',
    title: 'Database Migration - Media Platform',
    description: 'Migrate to new database schema',
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-4),
    actualDeploymentDate: getDateString(-4),
    createdDate: getDateString(-11),
    updatedDate: getDateString(-4),
    completedDate: getDateString(-4),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 16,
    crfNumber: 'CRF-2024-014',
    title: 'Pilot Program - AI Features',
    description: 'Beta test of AI-powered analytics',
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    requestedBy: 25,
    requestedByName: 'Monica Allen',
    status: 'Pending',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(45),
    createdDate: getDateString(-2),
    clientCount: 3,
    successfulDeployments: 0,
  },
  {
    crfId: 17,
    crfNumber: 'CRF-2023-095',
    title: 'Legacy System Upgrade - Government Services',
    description: 'Critical security update for legacy system',
    versionId: 6,
    versionNumber: '3.0.7',
    versionName: 'Legacy Patch 7',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'Critical',
    scheduledDeploymentDate: getDateString(-320),
    actualDeploymentDate: getDateString(-320),
    createdDate: getDateString(-330),
    updatedDate: getDateString(-320),
    completedDate: getDateString(-320),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 18,
    crfNumber: 'CRF-2024-015',
    title: 'Multi-Region Deployment - Hospitality',
    description: 'Deploy across multiple geographic regions',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(0),
    actualDeploymentDate: getDateString(0),
    createdDate: getDateString(-10),
    updatedDate: getDateString(0),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 19,
    crfNumber: 'CRF-2024-016',
    title: 'Real Estate Platform Enhancement',
    description: 'New property listing features',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 13,
    requestedByName: 'Nicole White',
    status: 'Approved',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(20),
    createdDate: getDateString(-5),
    updatedDate: getDateString(-1),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 20,
    crfNumber: 'CRF-2024-017',
    title: 'Aerospace Systems Security Update',
    description: 'Enhanced encryption and access controls',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Scheduled',
    priority: 'High',
    scheduledDeploymentDate: getDateString(7),
    createdDate: getDateString(-9),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 21,
    crfNumber: 'CRF-2024-018',
    title: 'Agriculture Tech IoT Integration',
    description: 'IoT sensor integration and monitoring',
    versionId: 9,
    versionNumber: '3.1.8',
    versionName: 'Summer 2024 Hotfix',
    requestedBy: 2,
    requestedByName: 'Sarah Johnson',
    status: 'Completed',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-110),
    actualDeploymentDate: getDateString(-110),
    createdDate: getDateString(-120),
    updatedDate: getDateString(-110),
    completedDate: getDateString(-110),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 22,
    crfNumber: 'CRF-2024-019',
    title: 'Pharmaceutical Compliance Suite',
    description: 'FDA compliance tracking features',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-80),
    actualDeploymentDate: getDateString(-80),
    createdDate: getDateString(-90),
    updatedDate: getDateString(-80),
    completedDate: getDateString(-80),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 23,
    crfNumber: 'CRF-2024-020',
    title: 'Automotive Tech Safety Updates',
    description: 'Safety monitoring and alerts system',
    versionId: 14,
    versionNumber: '3.1.2',
    versionName: 'Spring 2024 Hotfix 2',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'Critical',
    scheduledDeploymentDate: getDateString(-190),
    actualDeploymentDate: getDateString(-190),
    createdDate: getDateString(-196),
    updatedDate: getDateString(-190),
    completedDate: getDateString(-190),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 24,
    crfNumber: 'CRF-2024-021',
    title: 'Gaming Platform Performance Boost',
    description: 'Latency reduction and server optimization',
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    requestedBy: 4,
    requestedByName: 'Emily Davis',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-6),
    actualDeploymentDate: getDateString(-6),
    createdDate: getDateString(-14),
    updatedDate: getDateString(-6),
    completedDate: getDateString(-6),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 25,
    crfNumber: 'CRF-2024-022',
    title: 'Construction Management Mobile App',
    description: 'New mobile app deployment',
    versionId: 12,
    versionNumber: '3.1.3',
    versionName: 'Spring 2024 Patch',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-173),
    actualDeploymentDate: getDateString(-173),
    createdDate: getDateString(-180),
    updatedDate: getDateString(-173),
    completedDate: getDateString(-173),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 26,
    crfNumber: 'CRF-2024-023',
    title: 'Bulk Security Patch - All Active Clients',
    description: 'Critical security vulnerability fix for all versions',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 8,
    requestedByName: 'Marcus Thompson',
    status: 'Approved',
    priority: 'Critical',
    scheduledDeploymentDate: getDateString(2),
    createdDate: getDateString(-3),
    updatedDate: getDateString(0),
    clientCount: 15,
    successfulDeployments: 0,
  },
  {
    crfId: 27,
    crfNumber: 'CRF-2024-024',
    title: 'Education Platform Integration',
    description: 'LMS integration and student portal updates',
    versionId: 3,
    versionNumber: '3.1.5',
    versionName: 'Summer 2024 Patch',
    requestedBy: 13,
    requestedByName: 'Nicole White',
    status: 'Completed',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-145),
    actualDeploymentDate: getDateString(-145),
    createdDate: getDateString(-155),
    updatedDate: getDateString(-145),
    completedDate: getDateString(-145),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 28,
    crfNumber: 'CRF-2024-025',
    title: 'Energy Systems SCADA Integration',
    description: 'Industrial control system integration',
    versionId: 4,
    versionNumber: '3.1.0',
    versionName: 'Spring 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-205),
    actualDeploymentDate: getDateString(-205),
    createdDate: getDateString(-215),
    updatedDate: getDateString(-205),
    completedDate: getDateString(-205),
    clientCount: 1,
    successfulDeployments: 1,
  },
  {
    crfId: 29,
    crfNumber: 'CRF-2024-026',
    title: 'Quarterly Update Wave 1',
    description: 'Q1 2025 standard updates - first wave',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 9,
    requestedByName: 'Amanda Rodriguez',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(25),
    createdDate: getDateString(-1),
    clientCount: 5,
    successfulDeployments: 0,
  },
  {
    crfId: 30,
    crfNumber: 'CRF-2024-027',
    title: 'Quarterly Update Wave 2',
    description: 'Q1 2025 standard updates - second wave',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 9,
    requestedByName: 'Amanda Rodriguez',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(32),
    createdDate: getDateString(-1),
    clientCount: 4,
    successfulDeployments: 0,
  },
  {
    crfId: 31,
    crfNumber: 'CRF-2023-092',
    title: 'Cloud Migration - Phase 1',
    description: 'Initial cloud infrastructure migration',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-95),
    actualDeploymentDate: getDateString(-95),
    createdDate: getDateString(-105),
    updatedDate: getDateString(-95),
    completedDate: getDateString(-95),
    clientCount: 3,
    successfulDeployments: 3,
  },
  {
    crfId: 32,
    crfNumber: 'CRF-2023-093',
    title: 'Cloud Migration - Phase 2',
    description: 'Secondary cloud infrastructure migration',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Completed',
    priority: 'High',
    scheduledDeploymentDate: getDateString(-87),
    actualDeploymentDate: getDateString(-87),
    createdDate: getDateString(-95),
    updatedDate: getDateString(-87),
    completedDate: getDateString(-87),
    clientCount: 2,
    successfulDeployments: 2,
  },
  {
    crfId: 33,
    crfNumber: 'CRF-2024-028',
    title: 'API Rate Limiting Enhancement',
    description: 'Implement advanced rate limiting for all clients',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 25,
    requestedByName: 'Monica Allen',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(0),
    actualDeploymentDate: getDateString(0),
    createdDate: getDateString(-8),
    updatedDate: getDateString(0),
    clientCount: 8,
    successfulDeployments: 3,
  },
  {
    crfId: 34,
    crfNumber: 'CRF-2024-029',
    title: 'Data Retention Policy Update',
    description: 'Implement new data retention and archival policies',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Approved',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(14),
    createdDate: getDateString(-6),
    updatedDate: getDateString(-2),
    clientCount: 20,
    successfulDeployments: 0,
  },
  {
    crfId: 35,
    crfNumber: 'CRF-2024-030',
    title: 'Failed Deployment Test Case',
    description: 'Test deployment that encountered database errors',
    versionId: 2,
    versionNumber: '3.2.0',
    versionName: 'Fall 2024 Release',
    requestedBy: 12,
    requestedByName: 'Tyler Anderson',
    status: 'Failed',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(-50),
    actualDeploymentDate: getDateString(-50),
    createdDate: getDateString(-55),
    updatedDate: getDateString(-50),
    completedDate: getDateString(-50),
    clientCount: 1,
    successfulDeployments: 0,
  },
  {
    crfId: 36,
    crfNumber: 'CRF-2024-031',
    title: 'Monitoring System Upgrade',
    description: 'Enhanced system monitoring and alerting',
    versionId: 10,
    versionNumber: '3.2.2',
    versionName: 'Winter 2024 Hotfix',
    requestedBy: 8,
    requestedByName: 'Marcus Thompson',
    status: 'Completed',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(-12),
    actualDeploymentDate: getDateString(-12),
    createdDate: getDateString(-18),
    updatedDate: getDateString(-12),
    completedDate: getDateString(-12),
    clientCount: 30,
    successfulDeployments: 30,
  },
  {
    crfId: 37,
    crfNumber: 'CRF-2024-032',
    title: 'Backup System Optimization',
    description: 'Improve backup performance and reliability',
    versionId: 1,
    versionNumber: '3.2.1',
    versionName: 'Winter 2024 Release',
    requestedBy: 1,
    requestedByName: 'John Smith',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(18),
    createdDate: getDateString(-4),
    clientCount: 25,
    successfulDeployments: 0,
  },
  {
    crfId: 38,
    crfNumber: 'CRF-2024-033',
    title: 'User Experience Refresh',
    description: 'UI/UX improvements across all modules',
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    requestedBy: 25,
    requestedByName: 'Monica Allen',
    status: 'Pending',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(50),
    createdDate: getDateString(0),
    clientCount: 5,
    successfulDeployments: 0,
  },
  {
    crfId: 39,
    crfNumber: 'CRF-2024-034',
    title: 'Mobile App Version 2.0',
    description: 'Major mobile application update',
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    requestedBy: 4,
    requestedByName: 'Emily Davis',
    status: 'Pending',
    priority: 'Medium',
    scheduledDeploymentDate: getDateString(40),
    createdDate: getDateString(-1),
    clientCount: 12,
    successfulDeployments: 0,
  },
  {
    crfId: 40,
    crfNumber: 'CRF-2024-035',
    title: 'Analytics Dashboard v3',
    description: 'Next generation analytics and reporting',
    versionId: 13,
    versionNumber: '3.2.3',
    versionName: 'Spring 2025 Preview',
    requestedBy: 25,
    requestedByName: 'Monica Allen',
    status: 'Draft',
    priority: 'Low',
    scheduledDeploymentDate: getDateString(60),
    createdDate: getDateString(2),
    clientCount: 0,
    successfulDeployments: 0,
  },
];

// Export for integration
export const expandedCRFData = {
  crfs: additionalCRFs,
};
